### ISSUE TITLE
Refactor endpoints

### ISSUE THREAD

**Issue by rodolfocugler** [rodolfocugler/rest-sftp#1]
Current, the API has the following endpoints:

- /api/ftp
- /api/image
- /api/structure
- /api/url

However, they should be better designed

**Comment by rodolfocugler-hexad** [comment]
The following endpoints were changed from-to:

- /api/ftp : /api/commands
- /api/url : /api/commands/url
- /api/structure : /api/tree

**Comment by rodolfocugler** [comment]
The following endpoints were changed from-to:

/api/ftp : /api/commands
/api/url : /api/commands/url
/api/structure : /api/tree
